
.\"Created with GNOME Manpages Editor Wizard gmanedit
.TH ip6tables-converter 8 "March 2015" "Johannes Hubertz" " "

.SH NAME
ip6tables-converter \- program to convert ip6tables commands from file to ip6tables-restore format

.SH SYNOPSIS
.B ip6tables-converter
.RI [ -s \  ip6tables-plain-file ]
.br

.SH DESCRIPTION
The 
.B ip6tables-converter
takes a regular file containing a series of ip6tables 
invocations and converts such a sequence to a format compatible with
the 
.B ip6tables-restore
command. No attempt is made to reorder the sequence of the commands,
especially nothing in the input is interpreted in any way.
All input lines not starting with "ip6tables" or "/sbin/ip6tables" 
are ignored. Any input lines starting with "#" are treated as comments
and therefore are ignored.


.PP
if \fBip6tables-converter\fP is run without any arguments, it tries to read a file named "rules" in workdir. That's the tribute to my way of doing.

Output generally is send to
.B stdout
for your convienience and nowhere else. So you can inspect it and write to file for later feeding the ip6tables-restore command.

.PP
Something needs to be mentioned:
.B ip6tables -E
intellectually still is an unsolved problem and not implemented for now, sorry. Thank you for any
.B hints
of how to do it, I can't imagine because of some lacks in my brain.

.SH "EXIT STATUS"
Normally ip6tables-converter returns a value of 0.
In accidential case of
.B errors
exit status 1 is returned. For example, if there are shell variables or shell functions
in the inputfile, these are treated as error, which is reported. To avoid these,
execute your scripts and feed their output as a file to ip6tables-converter.

.SH VERSIONS
ip6tables-converter
.B should
be compatibe to any ip6tables implementations out in the wild. If not, keep me informed, thanks. I'll do my very best.

.SH OPTIONS
.B -s filename
This option gives you a chance to take another filename instaed of "rules"

.SH AUTHOR
Johannes Hubertz <johannes@hubertz.de> wrote this in 2013, 2014, 2015.
Any comments welcome anytime.

.SH "SEE ALSO"
.BR ip6tables (8)
.BR ip6tables-save (8)
.BR ip6tables-restore (8)

