
.\"Created with GNOME Manpages Editor Wizard gmanedit
.TH ip6tables-converter 8 "Nov 2017" "Johannes Hubertz" " "

.SH NAME
ip6tables-converter \- program to convert iptables commands from file to iptables-restore format

.SH SYNOPSIS
.B ip6tables-converter
.RI [ -d \  output-file ]
.RI [ -s \  iptables-plain-file ]
.RI [ --sloppy ]
.br

.SH DESCRIPTION
The
.B ip6tables-converter
takes a regular file containing a series of iptables
invocations and converts such a sequence to a format compatible with
the
.B iptables-restore
command. No attempt is made to reorder the sequence of the commands,
especially nothing in the input is interpreted in any way.
All input lines not starting with "iptables" or "/sbin/iptables"
are ignored. Any input lines starting with "#" are treated as comments
and therefore are ignored.


.PP
if \fBip6tables-converter\fP is run without any arguments, it tries to read a file named "rules" in workdir. That's the tribute to my way of doing.

In absence of command-line option
.B -d
output is send to
.B stdout
for your convienience and nowhere else. So you can inspect it and write to file for later feeding the iptables-restore command.

.PP
Something needs to be mentioned:
.B iptables -E
intellectually still is an unsolved problem and not implemented for now, sorry. Thank you for any
.B hints
of how to do it, I can't imagine because of some lacks in my brain.

.SH "EXIT STATUS"
Normally ip6tables-converter returns a value of 0.
In accidential case of
.B errors
exit status 1 is returned. For example, if there are shell variables or shell functions
in the inputfile, these are treated as error, which is reported. To avoid these,
execute your scripts and feed their output as a file to ip6tables-converter.

.SH VERSIONS
ip6tables-converter
.B should
be compatibe to any iptables implementations out in the wild. If not, keep me informed, thanks. I'll do my very best.

.SH OPTIONS
.B -s filename
This option gives you a chance to take another filename instaed of "rules"

.B --sloppy
This indicates '-N UserChain' is not required prior to mentioning any UserChain input or append, the chain is build on the fly.
It was build in for special user request.

.SH AUTHOR
Johannes Hubertz <johannes@hubertz.de> wrote this from 2013 to 2017.
Any comments welcome anytime.

.SH "SEE ALSO"
.BR iptables (8)
.BR iptables-save (8)
.BR iptables-restore (8)

